"""Added additional fields to User model

Revision ID: a382d23cc5e1
Revises: ffdc0a98111c
Create Date: 2024-02-18 15:43:52.355892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a382d23cc5e1'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_creator', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('user_intro', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_intro')
        batch_op.drop_column('is_creator')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
