"""empty message

Revision ID: 7f336de96f7b
Revises: a719b7eca437
Create Date: 2024-02-24 11:56:19.984200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f336de96f7b'
down_revision = 'a719b7eca437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.alter_column('video_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.alter_column('video_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
